'use client';

import { useState } from 'react';
import { Sparkles, Loader2 } from 'lucide-react';

interface AISummaryProps {
  type: 'trial' | 'company' | 'news';
  data: any;
  compact?: boolean;
}

export function AISummary({ type, data, compact = false }: AISummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(false);

  const generateSummary = async () => {
    if (summary) {
      // If already generated, just expand/collapse
      setExpanded(!expanded);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const response = await fetch('/api/ai/summarize', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ type, data }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate summary');
      }

      const result = await response.json();
      setSummary(result.summary);
      setExpanded(true);
    } catch (err: any) {
      setError(err.message || 'Failed to generate AI summary');
    } finally {
      setLoading(false);
    }
  };

  if (compact) {
    return (
      <button
        onClick={generateSummary}
        disabled={loading}
        className="inline-flex items-center gap-1 px-3 py-1 text-sm bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-full hover:from-purple-700 hover:to-blue-700 disabled:opacity-50 transition-all"
      >
        {loading ? (
          <>
            <Loader2 className="h-3 w-3 animate-spin" />
            <span>Generating...</span>
          </>
        ) : (
          <>
            <Sparkles className="h-3 w-3" />
            <span>AI Summary</span>
          </>
        )}
      </button>
    );
  }

  return (
    <div className="mt-3 border-t pt-3">
      <button
        onClick={generateSummary}
        disabled={loading}
        className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-lg hover:from-purple-700 hover:to-blue-700 disabled:opacity-50 transition-all"
      >
        {loading ? (
          <>
            <Loader2 className="h-4 w-4 animate-spin" />
            <span>Generating AI Summary...</span>
          </>
        ) : summary ? (
          <>
            <Sparkles className="h-4 w-4" />
            <span>{expanded ? 'Hide' : 'Show'} AI Summary</span>
          </>
        ) : (
          <>
            <Sparkles className="h-4 w-4" />
            <span>Generate AI Summary</span>
          </>
        )}
      </button>

      {error && (
        <div className="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
          {error}
        </div>
      )}

      {summary && expanded && (
        <div className="mt-3 p-4 bg-gradient-to-br from-purple-50 to-blue-50 border border-purple-200 rounded-lg">
          <div className="flex items-start gap-2 mb-2">
            <Sparkles className="h-5 w-5 text-purple-600 flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold text-purple-900 mb-2">AI-Generated Summary</h4>
              <div className="text-gray-800 text-sm leading-relaxed whitespace-pre-line">
                {summary}
              </div>
            </div>
          </div>
          <p className="text-xs text-gray-500 mt-3">
            Generated by GPT-4o-mini • May contain inaccuracies
          </p>
        </div>
      )}
    </div>
  );
}

