'use client';

import { useState } from 'react';
import { Search, Sparkles, Loader2, ExternalLink, X } from 'lucide-react';

interface Source {
  type: string;
  id: string;
  title: string;
  url: string;
  metadata?: Record<string, any>;
  relevance: string;
}

interface SearchResponse {
  answer: string;
  sources: Source[];
  query: string;
  model?: string;
  tokensUsed?: { input: number; output: number };
  estimatedCost?: number;
}

export default function AskCompeteAI() {
  const [query, setQuery] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [result, setResult] = useState<SearchResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isExpanded, setIsExpanded] = useState(false);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!query.trim()) return;

    setIsSearching(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch('/api/ai/search', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query: query.trim() }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to search');
      }

      const data: SearchResponse = await response.json();
      setResult(data);
      setIsExpanded(true);
    } catch (err: any) {
      setError(err.message || 'An error occurred while searching');
    } finally {
      setIsSearching(false);
    }
  };

  const clearResult = () => {
    setResult(null);
    setError(null);
    setQuery('');
    setIsExpanded(false);
  };

  return (
    <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
      {/* Header */}
      <div className="p-4 border-b border-gray-200">
        <div className="flex items-center gap-2 mb-2">
          <Sparkles className="w-5 h-5 text-purple-600" />
          <h3 className="font-semibold text-gray-900">Ask CompeteAI</h3>
        </div>
        <p className="text-xs text-gray-500">
          Natural language search across trials, companies, news & indications
        </p>
      </div>

      {/* Search Form */}
      <form onSubmit={handleSearch} className="p-4">
        <div className="flex gap-2">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="e.g., What are Pfizer's Phase 3 oncology trials?"
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent text-sm"
              disabled={isSearching}
            />
          </div>
          <button
            type="submit"
            disabled={isSearching || !query.trim()}
            className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-sm font-medium flex items-center gap-2"
          >
            {isSearching ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Searching...
              </>
            ) : (
              'Search'
            )}
          </button>
        </div>
      </form>

      {/* Error Message */}
      {error && (
        <div className="px-4 pb-4">
          <div className="bg-red-50 border border-red-200 rounded-lg p-3">
            <p className="text-sm text-red-800">{error}</p>
          </div>
        </div>
      )}

      {/* Results */}
      {result && isExpanded && (
        <div className="border-t border-gray-200">
          {/* Answer */}
          <div className="p-4 bg-gradient-to-br from-purple-50 to-blue-50">
            <div className="flex items-start justify-between mb-2">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-purple-600" />
                <span className="text-xs font-medium text-gray-700">Answer</span>
              </div>
              <button
                onClick={clearResult}
                className="text-gray-400 hover:text-gray-600"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
            <p className="text-sm text-gray-800 leading-relaxed whitespace-pre-wrap">
              {result.answer}
            </p>
            {result.model && (
              <p className="text-xs text-gray-500 mt-2">
                Generated by {result.model} • 
                {result.tokensUsed && (
                  <> {result.tokensUsed.input + result.tokensUsed.output} tokens • </>
                )}
                {result.estimatedCost && (
                  <> ${result.estimatedCost.toFixed(4)} estimated cost</>
                )}
              </p>
            )}
          </div>

          {/* Sources */}
          {result.sources && result.sources.length > 0 && (
            <div className="p-4">
              <h4 className="text-xs font-semibold text-gray-700 mb-3">
                Sources ({result.sources.length})
              </h4>
              <div className="space-y-2">
                {result.sources.map((source, index) => (
                  <a
                    key={index}
                    href={source.url}
                    target={source.url.startsWith('http') ? '_blank' : undefined}
                    rel={source.url.startsWith('http') ? 'noopener noreferrer' : undefined}
                    className="block p-3 bg-gray-50 hover:bg-gray-100 rounded-lg border border-gray-200 transition-colors group"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <span className="text-xs font-medium text-purple-600 uppercase">
                            {source.type}
                          </span>
                          <span className="text-xs text-gray-500">
                            {parseFloat(source.relevance) * 100}% relevant
                          </span>
                        </div>
                        <p className="text-sm text-gray-900 font-medium truncate group-hover:text-purple-600">
                          {source.title}
                        </p>
                        {source.metadata && Object.keys(source.metadata).length > 0 && (
                          <div className="mt-1 flex flex-wrap gap-1">
                            {Object.entries(source.metadata)
                              .slice(0, 3)
                              .map(([key, value]) => (
                                <span
                                  key={key}
                                  className="text-xs px-2 py-0.5 bg-gray-200 text-gray-600 rounded"
                                >
                                  {key}: {Array.isArray(value) ? value.join(', ') : String(value)}
                                </span>
                              ))}
                          </div>
                        )}
                      </div>
                      {source.url && (
                        <ExternalLink className="w-4 h-4 text-gray-400 group-hover:text-purple-600 ml-2 flex-shrink-0" />
                      )}
                    </div>
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Example Queries */}
      {!result && !isSearching && (
        <div className="px-4 pb-4">
          <p className="text-xs text-gray-500 mb-2">Try asking:</p>
          <div className="space-y-1">
            {[
              "What are Pfizer's Phase 3 oncology trials?",
              "Latest FDA approvals in immunology?",
              "Compare Roche and Novartis in oncology",
            ].map((example, index) => (
              <button
                key={index}
                onClick={() => setQuery(example)}
                className="block w-full text-left text-xs text-gray-600 hover:text-purple-600 px-2 py-1 rounded hover:bg-gray-50 transition-colors"
              >
                "{example}"
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
